import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useAppDispatch, useAppSelector } from 'src/store'
import { selectCount } from 'src/store/counter'
import { increment, setCounterState } from 'src/store/counter/counterSlice'
import { NextSeo } from 'next-seo'

export const getStaticProps: GetStaticProps = async () => ({
  props: { data: ['Karthick', 'Ragavendran'] }, // will be passed to the page component as props
})

const Home: NextPage = ({
  data,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const obj = { title: 'Hello World' }
  const [text, setText] = useState(JSON.stringify(obj))
  const dispatch = useAppDispatch()
  const count = useAppSelector(selectCount)
  useEffect(() => {
    dispatch(setCounterState(data))
  }, [data, dispatch])
  return (
    <div>
      {JSON.stringify(count)}
      {text}
      <NextSeo
        title='Next boilerplate.'
        description='A short description goes here which says what goes here.'
      />
      {/** @ts-ignore */}
      <button type='button' onClick={() => setText(obj)}>
        Break things
      </button>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <button
        className='px-2 py-1 border rounded-sm'
        type='button'
        onClick={() => dispatch(setCounterState(8))}
      >
        Click{' '}
      </button>
      <button
        className='px-2 py-1 border rounded-sm'
        type='button'
        onClick={() => dispatch(increment())}
      >
        Inc{' '}
      </button>

      <main>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>

        <div>
          <a href='https://nextjs.org/docs'>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn'>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/master/examples'>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <Link prefetch={false} href='/sample'>
          <a>To sample page </a>
        </Link>
      </main>

      <footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
